openapi: 3.0.0
info:
  title: httpbin.org
  description: API Management facade for a very handy and free online HTTP tool.
  version: "1.0"
paths:
  "/status/{code}":
    get:
      description: Returns provided HTTP Status code.
      operationId: /status
      parameters:
        - name: code
          in: path
          description: HTTP code to return.
          required: true
          schema:
            type: number
            enum:
              - 200
            default: 200
      responses:
        '200':
          description: OK
  /get:
    get:
      description: Returns GET data.
      operationId: /get
      responses:
        '200':
          description: OK
  /post:
    post:
      description: Returns POST data.
      operationId: /post
      responses:
        '200':
          description: OK
  /patch:
    patch:
      description: Returns PATCH data.
      operationId: /patch
      responses:
        '200':
          description: OK
  /put:
    put:
      description: Returns PUT data.
      operationId: /put
      responses:
        '200':
          description: OK
  /delete:
    delete:
      description: Returns DELETE data.
      operationId: /delete
      responses:
        '200':
          description: OK
  /xml:
    get:
      description: Returns some XML.
      operationId: /xml
      responses:
        '200':
          description: OK
  /ip:
    get:
      description: Returns origin IP.
      operationId: /ip
      responses:
        '200':
          description: OK
  /user-agent:
    get:
      description: Returns user agent string.
      operationId: /user-agent
      responses:
        '200':
          description: OK
  /headers:
    get:
      description: Returns headers dictionary.
      operationId: /headers
      responses:
        '200':
          description: OK
  "/delay/{seconds}":
    get:
      description: Delays responding for n–10 seconds.
      operationId: /delay
      parameters:
        - name: seconds
          in: path
          description: ""
          required: true
          schema:
            type: string
            enum:
              - 2
            default: 2
      responses:
        '200':
          description: OK
  "/cache/{maxAge}":
    get:
      operationId: /cache
      description: Sets a Cache-Control header for n seconds.
      parameters:
        - name: maxAge
          in: path
          description: ""
          required: true
          schema:
            type: string
            enum:
              - 10
            default: 10
      responses:
        '200':
          description: OK
  /uuid:
    get:
      operationId: /uuid
      description: Returns UUID4.
      responses:
        '200':
          description: OK
  /anything:
    get:
      operationId: /anything
      description: Returns request data, including method used.
      responses:
        '200':
          description: OK
  /gzip:
    get:
      operationId: /gzip
      description: Returns gzip-encoded data.
      responses:
        '200':
          description: OK
  "/base64/{value}":
    get:
      operationId: /base64
      description: Decodes base64url-encoded string.
      parameters:
        - name: value
          in: path
          description: Base64 encoded string.
          required: true
          schema:
            type: string
            default: aGVsbG8gd29ybGQNCg%3D%3D
      responses:
        '200':
          description: OK
  /deflate:
    get:
      operationId: /deflate
      description: Returns deflate-encoded data.
      responses:
        '200':
          description: OK
  /brotli:
    get:
      operationId: /brotli
      description: Returns brotli-encoded data.
      responses:
        '200':
          description: OK
  /response-headers:
    get:
      operationId: /response-headers
      description: Returns key-value query parameters as response headers.
      responses:
        '200':
          description: OK
  "/bytes/{number}":
    get:
      operationId: /bytes
      description: Generates n random bytes of binary data
      parameters:
        - name: number
          in: path
          description: Number of bytes to return.
          required: true
          schema:
            type: string
            default: "1024"
      responses:
        '200':
          description: OK
  /redirect-to:
    get:
      operationId: /redirect-to
      description: 302 redirects to a URL provided in query
      parameters:
        - name: url
          in: query
          description: Redirect target
          required: true
          schema:
            type: string
            default: http://example.com
      responses:
        '200':
          description: OK
  "/stream/{number}":
    get:
      operationId: /stream
      description: Streams min(number, 100) lines.
      parameters:
        - name: number
          in: path
          description: Number of lines to stream.
          required: true
          schema:
            type: number
            default: "10"
      responses:
        '200':
          description: OK
servers:
  - url: http://httpbin.org
  - url: https://httpbin.org