// Auto-generated by the Load Impact converter

import "./libs/shim/core.js";
import "./libs/shim/urijs.js";

export let options = { maxRedirects: 4, iterations: "100" };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  collection: {
    undefined: "http://httpbin.org"
  }
});

export default function() {
  postman[Request]({
    name: "/status",
    id: "40aee45a-c07b-4174-8ece-1a3083795e97",
    method: "GET",
    address: "{{baseUrl}}/status/<number>"
  });

  postman[Request]({
    name: "/get",
    id: "f1a4fd4e-860f-479c-b7d2-daa29a171941",
    method: "GET",
    address: "{{baseUrl}}/get"
  });

  postman[Request]({
    name: "/post",
    id: "3d8b3e2e-f47d-4a92-b9f0-f87002864b7f",
    method: "POST",
    address: "{{baseUrl}}/post"
  });

  postman[Request]({
    name: "/patch",
    id: "4fdda4e2-3245-4c9d-a18b-01af37843675",
    method: "PATCH",
    address: "{{baseUrl}}/patch"
  });

  postman[Request]({
    name: "/put",
    id: "25f3b5bb-d446-423e-8db4-2e09452c3bf7",
    method: "PUT",
    address: "{{baseUrl}}/put"
  });

  postman[Request]({
    name: "/delete",
    id: "2915c59c-a961-4f23-9375-530ea9cabb26",
    method: "DELETE",
    address: "{{baseUrl}}/delete"
  });

  postman[Request]({
    name: "/xml",
    id: "e7ddf23f-15ee-4e94-b09d-66ab73ed8fc0",
    method: "GET",
    address: "{{baseUrl}}/xml"
  });

  postman[Request]({
    name: "/ip",
    id: "fa915a53-5a4a-4cbb-86d5-72e5ac18d9b8",
    method: "GET",
    address: "{{baseUrl}}/ip"
  });

  postman[Request]({
    name: "/user-agent",
    id: "f6c08c1e-3b40-45ca-a21f-dedfb4a6468b",
    method: "GET",
    address: "{{baseUrl}}/user-agent"
  });

  postman[Request]({
    name: "/headers",
    id: "6be071b7-0ef1-4b69-9827-581bba5bf274",
    method: "GET",
    address: "{{baseUrl}}/headers"
  });

  postman[Request]({
    name: "/delay",
    id: "fcaea5a7-152d-401e-9f81-4059626ba746",
    method: "GET",
    address: "{{baseUrl}}/delay/:seconds"
  });

  postman[Request]({
    name: "/cache",
    id: "1a6fc253-cc93-4534-9e0d-090eddd30b7c",
    method: "GET",
    address: "{{baseUrl}}/cache/:maxAge"
  });

  postman[Request]({
    name: "/uuid",
    id: "f35b7856-35f3-47e5-9a4c-9de1bf7a48ad",
    method: "GET",
    address: "{{baseUrl}}/uuid"
  });

  postman[Request]({
    name: "/anything",
    id: "7aef9e17-845f-485a-8b8f-94ed34601475",
    method: "GET",
    address: "{{baseUrl}}/anything"
  });

  postman[Request]({
    name: "/gzip",
    id: "b7dec360-b9ac-46bb-adc3-ebc3d1c0ba50",
    method: "GET",
    address: "{{baseUrl}}/gzip"
  });

  postman[Request]({
    name: "/base64",
    id: "e074927f-8af4-47ff-b9f7-2937db30b89a",
    method: "GET",
    address: "{{baseUrl}}/base64/aGVsbG8gd29ybGQNCg%3D%3D"
  });

  postman[Request]({
    name: "/deflate",
    id: "8c5221fa-a770-4c7b-b42a-73c056cddac0",
    method: "GET",
    address: "{{baseUrl}}/deflate"
  });

  postman[Request]({
    name: "/brotli",
    id: "3ff8e290-9038-4dbb-83bd-132df8d15eda",
    method: "GET",
    address: "{{baseUrl}}/brotli"
  });

  postman[Request]({
    name: "/response-headers",
    id: "c44e681b-6ea0-4181-80d9-7d848e173bd5",
    method: "GET",
    address: "{{baseUrl}}/response-headers"
  });

  postman[Request]({
    name: "/bytes",
    id: "58483370-bcec-4db2-a173-72ee1f4d5218",
    method: "GET",
    address: "{{baseUrl}}/bytes/1024"
  });

  postman[Request]({
    name: "/redirect-to",
    id: "4a76e163-451f-4a0f-acae-ba77d12dbcdb",
    method: "GET",
    address: "{{baseUrl}}/redirect-to?url=http://example.com"
  });

  postman[Request]({
    name: "/stream",
    id: "6f7f890d-db4c-490f-b0b6-ff06cb317395",
    method: "GET",
    address: "{{baseUrl}}/stream/10"
  });
}
