// Auto-generated by the Load Impact converter

import "./libs/shim/core.js";
import "./libs/shim/urijs.js";

export let options = { maxRedirects: 4, iterations: 1000, vus: 100 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  collection: {
    baseUrl: "http://localhost:8080"
  }
});

export default function() {
  postman[Request]({
    name: "/status",
    id: "87c745af-90cd-403a-a169-4c45064bdf27",
    method: "GET",
    address: "{{baseUrl}}/status/:code"
  });

  postman[Request]({
    name: "/get",
    id: "bf4f141d-3a71-40f4-a5d4-285ad8168043",
    method: "GET",
    address: "{{baseUrl}}/get"
  });

  postman[Request]({
    name: "/post",
    id: "51858155-4f81-4e93-9afb-c52a370d5620",
    method: "POST",
    address: "{{baseUrl}}/post"
  });

  postman[Request]({
    name: "/patch",
    id: "8b1fb858-6a62-4e4b-88d1-dcad4150f463",
    method: "PATCH",
    address: "{{baseUrl}}/patch"
  });

  postman[Request]({
    name: "/put",
    id: "36ed0d1f-b302-474a-a9d1-dd73ee150587",
    method: "PUT",
    address: "{{baseUrl}}/put"
  });

  postman[Request]({
    name: "/delete",
    id: "cff3cbcb-287a-42fa-bb45-e159374c9467",
    method: "DELETE",
    address: "{{baseUrl}}/delete"
  });

  postman[Request]({
    name: "/xml",
    id: "6b8ca47f-90ec-44bf-aab1-9a2fd9296954",
    method: "GET",
    address: "{{baseUrl}}/xml"
  });

  postman[Request]({
    name: "/ip",
    id: "b9ad2012-f320-487a-ba0c-5b93f88359fe",
    method: "GET",
    address: "{{baseUrl}}/ip"
  });

  postman[Request]({
    name: "/user-agent",
    id: "f62b8361-6fef-460f-a660-99a5cc8e1d37",
    method: "GET",
    address: "{{baseUrl}}/user-agent"
  });

  postman[Request]({
    name: "/headers",
    id: "3fa150ac-539a-45a3-bbdd-a6e2bc4d3588",
    method: "GET",
    address: "{{baseUrl}}/headers"
  });

  postman[Request]({
    name: "/delay",
    id: "4692d42d-ac7b-4c7b-b661-54fb3b466491",
    method: "GET",
    address: "{{baseUrl}}/delay/:seconds"
  });

  postman[Request]({
    name: "/cache",
    id: "29d9d255-9735-4798-a496-169a2f3a70e1",
    method: "GET",
    address: "{{baseUrl}}/cache/:maxAge"
  });

  postman[Request]({
    name: "/uuid",
    id: "7497bcb8-8fb3-4fbd-b986-5085cf997aa8",
    method: "GET",
    address: "{{baseUrl}}/uuid"
  });

  postman[Request]({
    name: "/anything",
    id: "23ae4a15-1e43-49e1-8528-12e07e676a8e",
    method: "GET",
    address: "{{baseUrl}}/anything"
  });

  postman[Request]({
    name: "/gzip",
    id: "36e4ab9a-0d59-4979-a735-185d7aca29b2",
    method: "GET",
    address: "{{baseUrl}}/gzip"
  });

  postman[Request]({
    name: "/base64",
    id: "d087f525-8099-40d2-9b99-e5215b276509",
    method: "GET",
    address: "{{baseUrl}}/base64/aGVsbG8gd29ybGQNCg%3D%3D"
  });

  postman[Request]({
    name: "/deflate",
    id: "821c8034-7c71-46b8-b05e-f2c913a59c0d",
    method: "GET",
    address: "{{baseUrl}}/deflate"
  });

  postman[Request]({
    name: "/brotli",
    id: "f33d8c92-0ac6-45e6-89cb-8c3c47523045",
    method: "GET",
    address: "{{baseUrl}}/brotli"
  });

  postman[Request]({
    name: "/response-headers",
    id: "abdb1b42-01b9-4290-8a4d-d730f6289bd0",
    method: "GET",
    address: "{{baseUrl}}/response-headers"
  });

  postman[Request]({
    name: "/bytes",
    id: "73a45dc4-14a8-4237-bed0-cb7f0a2f2da9",
    method: "GET",
    address: "{{baseUrl}}/bytes/1024"
  });

  postman[Request]({
    name: "/redirect-to",
    id: "fffe2f8f-668f-40c6-85b5-84251b6753b5",
    method: "GET",
    address: "{{baseUrl}}/redirect-to?url=http://example.com"
  });

  postman[Request]({
    name: "/stream",
    id: "cf4cfce2-140d-4d98-b1e3-6c98ac580c4b",
    method: "GET",
    address: "{{baseUrl}}/stream/10"
  });
}
