// Auto-generated by the Load Impact converter

import "./libs/shim/core.js";
import "./libs/shim/urijs.js";

export let options = { maxRedirects: 4, iterations: "100" };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  collection: {
    undefined: "http://httpbin.org"
  }
});

export default function() {
  postman[Request]({
    name: "/status",
    id: "d1ecd841-d8e3-49b1-ae80-19913c2502b9",
    method: "GET",
    address: "{{baseUrl}}/status/<number>"
  });

  postman[Request]({
    name: "/get",
    id: "65212602-3ea4-47e8-bdd8-9f9cbdba0213",
    method: "GET",
    address: "{{baseUrl}}/get"
  });

  postman[Request]({
    name: "/post",
    id: "f30eeee2-26d0-4d95-8397-4c45b7d10baa",
    method: "POST",
    address: "{{baseUrl}}/post"
  });

  postman[Request]({
    name: "/patch",
    id: "69d108bd-8503-4a17-b13c-b03ee9c60a74",
    method: "PATCH",
    address: "{{baseUrl}}/patch"
  });

  postman[Request]({
    name: "/put",
    id: "a2e2e7f6-2cf0-4d81-85c2-38306f7f61fb",
    method: "PUT",
    address: "{{baseUrl}}/put"
  });

  postman[Request]({
    name: "/delete",
    id: "25e99110-9388-4917-9239-5bede7051197",
    method: "DELETE",
    address: "{{baseUrl}}/delete"
  });

  postman[Request]({
    name: "/xml",
    id: "e6798443-34a3-4ae3-83ac-e096e7463e7a",
    method: "GET",
    address: "{{baseUrl}}/xml"
  });

  postman[Request]({
    name: "/ip",
    id: "5671eecf-ef9d-4c3d-94ef-f1e9b5f9d9c5",
    method: "GET",
    address: "{{baseUrl}}/ip"
  });

  postman[Request]({
    name: "/user-agent",
    id: "b723bc53-bffe-4b90-a6b7-f12f4742898b",
    method: "GET",
    address: "{{baseUrl}}/user-agent"
  });

  postman[Request]({
    name: "/headers",
    id: "fa2d11eb-da36-47d1-b819-de9f270efcdc",
    method: "GET",
    address: "{{baseUrl}}/headers"
  });

  postman[Request]({
    name: "/delay",
    id: "740cd155-8cf7-478e-b205-de554bec2eaa",
    method: "GET",
    address: "{{baseUrl}}/delay/:seconds"
  });

  postman[Request]({
    name: "/cache",
    id: "5ec574e7-ebec-4724-a97c-ccb60ac3461f",
    method: "GET",
    address: "{{baseUrl}}/cache/:maxAge"
  });

  postman[Request]({
    name: "/uuid",
    id: "2c6b4cee-d572-4240-b74e-483cc0faf26a",
    method: "GET",
    address: "{{baseUrl}}/uuid"
  });

  postman[Request]({
    name: "/anything",
    id: "efe83529-35d8-4fe7-a477-aeee43a7cd43",
    method: "GET",
    address: "{{baseUrl}}/anything"
  });

  postman[Request]({
    name: "/gzip",
    id: "a3fe8bd4-7dc7-407e-b470-9491d9d41506",
    method: "GET",
    address: "{{baseUrl}}/gzip"
  });

  postman[Request]({
    name: "/base64",
    id: "29304b3f-abd0-44b6-9061-f970baa794cd",
    method: "GET",
    address: "{{baseUrl}}/base64/aGVsbG8gd29ybGQNCg%3D%3D"
  });

  postman[Request]({
    name: "/deflate",
    id: "8379f5ab-31fc-40b8-b5da-898c9c209fd2",
    method: "GET",
    address: "{{baseUrl}}/deflate"
  });

  postman[Request]({
    name: "/brotli",
    id: "911cc3a4-659e-4960-a6d4-11288a2ce923",
    method: "GET",
    address: "{{baseUrl}}/brotli"
  });

  postman[Request]({
    name: "/response-headers",
    id: "60b140e4-be7c-49c5-908b-56e8bd19f23d",
    method: "GET",
    address: "{{baseUrl}}/response-headers"
  });

  postman[Request]({
    name: "/bytes",
    id: "31db0ad6-9900-4de2-aaf5-f6cd5118ddec",
    method: "GET",
    address: "{{baseUrl}}/bytes/1024"
  });

  postman[Request]({
    name: "/redirect-to",
    id: "ec96d5b4-4ae4-490b-8542-2d827d7d9006",
    method: "GET",
    address: "{{baseUrl}}/redirect-to?url=http://example.com"
  });

  postman[Request]({
    name: "/stream",
    id: "4ac2d6cc-3005-4e37-b134-bed1ad523898",
    method: "GET",
    address: "{{baseUrl}}/stream/10"
  });
}
